export const API_ROUTES = {
    LOGIN: '/api/login',
    REFRESH: '/api/token/refresh',
    REGISTER: '/api/register',
    MAGIC_LINK_REQUEST: '/api/auth/magic-link/request',
    ME: '/api/me',
    USERS_CREATE: '/api/users',
    USERS_GET: (id) => `/api/users/${id}`,
    REQUESTS_CREATE: '/api/requests',
    REQUESTS_GET: (id) => `/api/requests/${id}`,
    REQUESTS_MINE: '/api/requests/mine',
    REQUESTS_MATCHES: (id) => `/api/requests/${id}/matches`,
    CHATS_START: (userId) => `/api/chats/${userId}/start`,
    CHATS_LIST: '/api/chats',
    CHAT_MESSAGES: (chatId) => `/api/chats/${chatId}/messages`,
    CHAT_SEND_MESSAGE: (chatId) => `/api/chats/${chatId}/messages`,
    CHAT_MARK_READ: (chatId, messageId) => `/api/chats/${chatId}/messages/${messageId}/read`,
    CHAT_PARTICIPANTS: (chatId) => `/api/chats/${chatId}/participants`,
    FEEDBACK_APP: '/api/feedback/app',
    FEEDBACK_MATCH: '/api/feedback/match',
};
